### PR TITLE
fix(ReporterUtils): filename extraction for component testing

### LINKED ISSUE #46: Issue with file path with Cypress component testing
**Describe the bug**
Running this reporter with Cypress CT results in this:

```
could not find spec filename from title: redacted or from 'suite.invocationDetails'
Error: could not find spec filename from title: redacted or from 'suite.invocationDetails'
    at throwError (/home/redacted/redacted/node_modules/.pnpm/cypress-sonarqube-reporter@1.12.0_cypress@12.15.0/node_modules/cypress-sonarqube-reporter/src/ReporterUtils.js:25:11)
    at extractSpecFromSuite (/home/redacted/redacted/node_modules/.pnpm/cypress-sonarqube-reporter@1.12.0_cypress@12.15.0/node_modules/cypress-sonarqube-reporter/src/ReporterUtils.js:51:9)
    at SonarQubeCypressReporter.traverseSuite (/home/redacted/redacted/node_modules/.pnpm/cypress-sonarqube-reporter@1.12.0_cypress@12.15.0/node_modules/cypress-sonarqube-reporter/src/SonarQubeCypressReporter.js:71:33)
    at /home/redacted/redacted/node_modules/.pnpm/cypress-sonarqube-reporter@1.12.0_cypress@12.15.0/node_modules/cypress-sonarqube-reporter/src/SonarQubeCypressReporter.js:82:18
    at Array.forEach (<anonymous>)
    at SonarQubeCypressReporter.traverseSuite (/home/redacted/redacted/node_modules/.pnpm/cypress-sonarqube-reporter@1.12.0_cypress@12.15.0/node_modules/cypress-sonarqube-reporter/src/SonarQubeCypressReporter.js:81:22)
    at SonarQubeCypressReporter.onDone (/home/redacted/redacted/node_modules/.pnpm/cypress-sonarqube-reporter@1.12.0_cypress@12.15.0/node_modules/cypress-sonarqube-reporter/src/SonarQubeCypressReporter.js:58:14)
    at L.<anonymous> (/home/redacted/redacted/node_modules/.pnpm/cypress-sonarqube-reporter@1.12.0_cypress@12.15.0/node_modules/cypress-sonarqube-reporter/src/SonarQubeCypressReporter.js:45:18)
    at Object.onceWrapper (node:events:642:26)
    at L.emit (node:events:539:35)
    at E.emit (<embedded>:4582:16654)
    at Object.onMocha (<embedded>:4629:389133)
    at p.<anonymous> (<embedded>:4629:30585)
    at p.emit (node:events:527:28)
    at p.emitUntyped (<embedded>:4340:84346)
    at <embedded>:4340:91863
    at process.processTicksAndRejections (node:internal/process/task_queues:78:11)
```

From what I've seen, there is no useful filepath anywhere in the suite given to this function (or the function before this) except in the `parent`.
Locally, this change works, as expected:
```diff
--- a/src/ReporterUtils.js
+++ b/src/ReporterUtils.js
@@ -27,6 +27,7 @@ const throwError = (message) => {

 /**
  * Extract the spec file path from the suite.
+ * May ignore the options.useAbsoluteSpecPath if the requested is not available.
  * Raise an error if the spec could not be extracted.
  *
  * @param {object} suite the Mocha suite
@@ -41,8 +42,10 @@ const extractSpecFromSuite = (suite, options) => {
     if (index > -1) {
         spec = JSON.parse(title.substring(index + tag.length, title.lastIndexOf(']')));
         spec = options.useAbsoluteSpecPath ? spec.absolute : spec.relative;
-    } else if (suite.invocationDetails) {
+    } else if (suite.invocationDetails && (suite.invocationDetails.absoluteFile || suite.invocationDetails.relativeFile)) {
         spec = options.useAbsoluteSpecPath ? suite.invocationDetails.absoluteFile : suite.invocationDetails.relativeFile;
+    } else if (suite.parent && suite.parent.file) {
+        spec = suite.parent.file;
     } else {
         throwError(`could not find spec filename from title: ${title} or from 'suite.invocationDetails'`);
     }
```

I am not sure if this is really a fix (if so, I'd happily open a PR) or just a workaround.

### PR DESCRIPTION
**Pull request by Sett17**
Fixes an issue with extracting the spec filename from the suite in component testing. The code now properly handles cases where the requested spec is not available and falls back to using the parent suite's file as the spec filename.

Fixes #46

### CODE REVIEW

File: src/ReporterUtils.js [hunk 1]
```diff
@@ -41,8 +42,10 @@ const extractSpecFromSuite = (suite, options) => {
     if (index > -1) {
         spec = JSON.parse(title.substring(index + tag.length, title.lastIndexOf(']')));
         spec = options.useAbsoluteSpecPath ? spec.absolute : spec.relative;
-    } else if (suite.invocationDetails) {
+    } else if (suite.invocationDetails && (suite.invocationDetails.absoluteFile || suite.invocationDetails.relativeFile)) {
```
Comment (BBE78) [inline src/ReporterUtils.js:45]: Prefer the usage of optional chaining in that case
```javascript
else if (suite.invocationDetails?.absoluteFile || suite.invocationDetails?.relativeFile)
```

File: src/ReporterUtils.js [hunk 2]
```diff
@@ -41,8 +42,10 @@ const extractSpecFromSuite = (suite, options) => {
...
         spec = options.useAbsoluteSpecPath ? suite.invocationDetails.absoluteFile : suite.invocationDetails.relativeFile;
+    } else if (suite.parent && suite.parent.file) {
```
Comment (BBE78) [inline src/ReporterUtils.js:47]: Prefer the use of optional chaining:
```javascript
else if (suite.parent?.file)
```

File: src/ReporterUtils.js
Comment (BBE78) [inline src/ReporterUtils.js:1]: Add a test case with a Cypress component test to verify the modification

**Review by BBE78 — CHANGES_REQUESTED** [review]

**Comment by BBE78** [comment]
Hi @Sett17, thanks for your code fix proposal. Could you please setup a test case with Cypress component test to cover this fix?

**Comment by Sett17** [comment]
> Hi @Sett17, thanks for your code fix proposal. Could you please setup a test case with Cypress component test to cover this fix?

Hey, do you mean actually adding a minimal app with a ct that can be tested? Or just another case in the `ReporterUtils.spec.js`

File: src/ReporterUtils.js
Comment (Sett17) [reply src/ReporterUtils.js:1]: Hey, do you mean actually adding a minimal app with a ct that can be tested? Or just another case in the ReporterUtils.spec.js

Comment (fcuenya) [reply src/ReporterUtils.js:1]: It seems like only the later would be feasible, as the only way to fully reproduce the original issue would be setting up a sample project with CTs and running the reporter on it. 

That would likely fall outside of the testing scope for this codebase, but I would like to know if you think otherwise.

I am having this exact same issue with the usage of this tool and would really appreciate to get this fix going through, that is why I decided to chime in 🙂

**Review by fcuenya — APPROVED** [review]

File: src/ReporterUtils.js
Comment (Sett17) [reply src/ReporterUtils.js:1]: @BBE78 Hey, any thoughts on this? If you'd like a minimal app in this, some guidance on where and how that should live would be appreciated.

Comment (BBE78) [reply src/ReporterUtils.js:1]: Hi @Sett17, a Jest test on the reporter is a good start point but not enough to me because it is not executed into a Cypress env.
Since it seems to be linked to Cypress Component tests, then a dedicated spec should be created to verify that the problem is correctly addressed by this fix

**Comment by Sett17** [comment]
@BBE78 I hope I understood you correctly and that this is what you are looking for.

**Comment by BBE78** [comment]
Great @Sett17 ! Looks good to me.
Maybe we could add something inside the README to say that with this PR, the reporter is now compatible with Cypress component testing, no ?
